name: Auto Deploy SEO Blog

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Blog Generator
        run: |
          python SEO-Blog-Creator/scraping/scraper.py  # Adjust if needed
          python SEO-Blog-Creator/keyword_extraction/seo_keywords.py
          python SEO-Blog-Creator/blog_generation/blog_writer.py
          python SEO-Blog-Creator/deployment/publish.py
